name: Try put json of badge
on: [ workflow_dispatch, push ]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        #echo "matrix=$( echo "$JSON" )" >> $GITHUB_OUTPUT
        run: |
          echo 'matrix={[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]}' >> $GITHUB_OUTPUT
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson( needs.setup.outputs.matrix ) }}
    steps:
      - run: |
          echo "${{ matrix.value }}"
  
