name: Try put json of badge
on: [ workflow_dispatch ]
jobs:
  generate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate *.svg file for badge
        uses: emibcn/badge-action@v2.0.2
        env:
          coverage_value: 99%
        with:
          label: Tests coverage
          status: ${{env.coverage_value}}%
          # right part color only
          color: ${{ false
            || env.coverage_value > 90 && 'green'
            || env.coverage_value > 80 && 'yellow,green'
            || env.coverage_value > 70 && 'yellow'
            || env.coverage_value > 60 && 'orange,yellow'
            || env.coverage_value > 50 && 'orange'
            || env.coverage_value > 40 && 'red,orange'
            || env.coverage_value > 30 && 'red,red,orange'
            || env.coverage_value > 20 && 'red,red,red,orange'
            || 'red' }}
          path: windows_Debug_x86.svg
      - name: Put *.svg file to Gists for badge
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.ACCESS_TO_GIST }}
          gist_id: 2af621bdd237231125e907ea81b1f8a8
          file_path: windows_Debug_x86.svg
