name: Build release and public result (Debug-x86) 
on: { push: { paths-ignore: [ 'README.md', '**/requirements.txt' ] }, workflow_dispatch }
# Configuration
env:
  strPlatform: x86 # or x64
  strConfiguration: Debug # or Release
jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: read # for "actions/checkout@v3" when GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v3

      - name: Set values (windows-latest)
        run: | # build from *.sln, all tests
          echo "dirTestExecutables=${{github.workspace}}\bin\${{env.strPlatform}}\${{env.strConfiguration}}" >> $env:GITHUB_ENV
          echo "strCfg=${{env.strPlatform}}-${{env.strConfiguration}}" >> $env:GITHUB_ENV

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build relese
        run: MSBuild . -noLogo -verbosity:quiet -m -p:Platform=${env:strPlatform} -p:Configuration=${env:strConfiguration}

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-build-release-${{env.strCfg}}
          path: |
            ${{env.dirTestExecutables}}\*.exe
