name: Build tests GoogleTest (Debug-x86) 
on: [workflow_dispatch]
# Configuration
env:
  strPlatform: x86 # or x64
  strConfiguration: Debug # or Release
jobs:
  build-tests-gtest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3          
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build tests
        run: MSBuild qa/UnitTest/UnitTest.sln -noLogo -verbosity:quiet -m -p:Platform=${env:strPlatform} -p:Configuration=${env:strConfiguration} 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        env: # build from *.sln, all tests
           dirTestExecutables: ${{github.workspace}}\qa\UnitTest\bin\${{env.strPlatform}}\${{env.strConfiguration}}
        with:
          name: artifact-build-tests-gtest-${{env.strPlatform}}-${{env.strConfiguration}}
          path: | # *.pdb for code coverage
            ${{env.dirTestExecutables}}\*.exe
            ${{env.dirTestExecutables}}\*.pdb
            !${{env.dirTestExecutables}}\StaticLibrary.pdb
