name: Collect source code tests coverage using OpenCppCoverage (debug-x86)
on: [push,workflow_dispatch]
# Configuration
env:
  strConfiguration: Debug # or Release
  strPlatform: x86 # or x64
  dirTestExecutables: ${{github.workspace}}\qa\UnitTest\bin\Debug # build from *.sln, all tests
  module0: GTest1.exe
  module1: GTestDefWindowProc.exe
  module2: GTestEmptyWorkingSet.exe
  module3: GTestMem.exe
  strNameOccSetupFile: OpenCppCoverageSetup-x86-0.9.9.0.exe
  strGhTagOccSetupFile: release-0.9.9.0 # from https://github.com/OpenCppCoverage/OpenCppCoverage/tags
  relSetupOcc: Occ
  strOccExecutable: OpenCppCoverage.exe
  dirHtmlReport: ${{github.workspace}}\HtmlReport
#  Linting Error: context "env" is not allowed here. available contexts are "github", "inputs", "secrets", "vars"
#  ffnOcc: ${{github.workspace}}\${{env.relSetupOcc}}\OpenCppCoverage.exe
jobs:
  collect-tests-code-coverage:
    runs-on: windows-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: read # for "actions/checkout@v3" when GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-tests-gtest-debug-x86.yml
          name: artifact-build-tests-gtest-${{env.strConfiguration}}-${{env.strPlatform}}
          path: ${{env.dirTestExecutables}}
          search_artifacts: true

      - name: Download tool
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "OpenCppCoverage/OpenCppCoverage"
          fileName: ${{env.strNameOccSetupFile}}
          tag: ${{env.strGhTagOccSetupFile}}

      # +-TODO: use ${env:RUNNER_TEMP} for output data
      - name: Install tool
        run: |
          dir "${{github.workspace}}\${env:strNameOccSetupFile}"
          echo ${env:RUNNER_TEMP}\${env:relSetupOcc}
          echo "${{github.workspace}}\${env:strNameOccSetupFile}" /VERYSILENT /DIR=${env:RUNNER_TEMP}\${env:relSetupOcc}
          ."${{github.workspace}}\${env:strNameOccSetupFile}" /VERYSILENT /DIR=${env:RUNNER_TEMP}\${env:relSetupOcc}
          ."${{github.workspace}}\${env:strNameOccSetupFile}" /VERYSILENT /DIR=${env:relSetupOcc}
          dir .
          dir ${env:RUNNER_TEMP}
          dir ${env:RUNNER_TEMP}\${env:relSetupOcc}

#      - name: Show debug
#        continue-on-error: true
#        run: |
#          echo "env:module0: ${env:module0}"
#          echo "module0: $module0"
#          $excluded_sources="--excluded_sources 'src\Main.h' --excluded_sources 'src\Legacy' --excluded_sources 'qa\UnitTest' --excluded_sources 'D:\a\_work' --excluded_sources 'C:\Program Files'"
#          echo "excluded_sources: $excluded_sources"
#          $env:ffnOcc="${env:RUNNER_TEMP}\${env:relSetupOcc}\${env:strOccExecutable}"
#          echo "env:ffnOcc 1: ${env:ffnOcc}"
#      - name: Show debug2
#        continue-on-error: true
#        run: |
#          echo "env:ffnOcc 2: ${env:ffnOcc}"

          # ."${env:ffnOcc}" -q $modules $excluded_sources $excluded_line_regex $export_type -- $program_to_run

      - name: show debug3
        continue-on-error: true
        run: |
          dir ${env:RUNNER_TEMP}\${env:relSetupOcc}
      - name: show debug33
        continue-on-error: true
        run: |
          dir ${env:RUNNER_TEMP}\${env:relSetupOcc}\${env:strOccExecutable}
      - name: show debug33
        continue-on-error: true
        run: |
          $env:ffnOcc="${env:RUNNER_TEMP}\${env:relSetupOcc}\${env:strOccExecutable}"
          dir ${env:ffnOcc}

      - name: Run tool
        continue-on-error: true # when fail test
        # TODO: multiline excluded_sources
        run: | # double launching because windows system hooks from AppCompat conflicts with gmock-win32 hooks
          .${env:dirTestExecutables}\${env:module0} --help > nul 2>&1
          .${env:dirTestExecutables}\${env:module1} --help > nul 2>&1
          .${env:dirTestExecutables}\${env:module2} --help > nul 2>&1
          .${env:dirTestExecutables}\${env:module3} --help > nul 2>&1
          $env:ffnOcc="${env:RUNNER_TEMP}\${env:relSetupOcc}\${env:strOccExecutable}"
          $modules="--modules ${env:dirTestExecutables}"
          $excluded_sources="--excluded_sources 'src\Main.h' --excluded_sources 'src\Legacy' --excluded_sources 'qa\UnitTest' --excluded_sources 'D:\a\_work' --excluded_sources 'C:\Program Files'"
          $excluded_line_regex="--excluded_line_regex .*@NOCOVERAGE.*"
          $export_type="--export_type html:${env:dirHtmlReport}"
          $program_to_run="${env:dirTestExecutables}\${env:module0} --gtest_brief=1"
          cd src
          ."${env:RUNNER_TEMP}\${env:relSetupOcc}\${env:strOccExecutable}" -q --modules ${env:dirTestExecutables} --excluded_sources "src\Main.h" --excluded_sources "src\Legacy" --excluded_sources "qa\UnitTest" --excluded_sources "D:\a\_work" --excluded_sources "C:\Program Files" --excluded_line_regex .*@NOCOVERAGE.* --export_type html:${{github.workspace}}\Coverage -- ${env:dirPathResult}\${env:module0} --gtest_brief=1

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-tests-coverage-open-cpp-coverage
          path: ${{env.dirHtmlReport}}
