name: Try peter-evans/repository-dispatch, events sender
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    # Main workflow job that builds, tests, etc.
    steps:
      - run: echo Work...
  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TO_PUBLIC_REPO }}
          repository: username/my-repo
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
