name: Try peter-evans/repository-dispatch, events sender
on: { workflow_dispatch, push: { paths-ignore: [ 'README.md', 'LICENSE' ] } }
# Configuration
env:
  strPlatform: x86 # or x64
  strConfiguration: Debug # or Release
jobs:
  build:
    runs-on: ubuntu-latest
    # Main workflow job that builds, tests, etc.
    steps:
      - run: echo Work...
  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set values (ubuntu-latest!!!!!!!!!!!!)
        run: | 
          echo "strCfg=${{env.strPlatform}}-${{env.strConfiguration}}" >> $GITHUB_ENV
# run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TO_PUBLIC_REPO }}
          repository: Alex0vSky/project-qa-report
          event-type: a0s_event_public_pages
          client-payload: |
            '{"project": "${{ github.event.repository.name }}", "repo": "${{ github.repository }}", "workflow": "${{ github.workflow_ref }}", "artifact": "artifact-coverage-tests-OpenCppCoverage-${{env.strCfg}}"}'
