name: Google Test
on: [workflow_dispatch]
jobs:
  google-tests:
    runs-on: windows-latest
    # for private GitHub repos
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build tests
        # only one for speedup
        run: MSBuild qa\UnitTest\GTestMem -m -p:Configuration=Debug
      - name: Run tests and collect reports
        run: |
          "${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\x64\Debug\GTestMem.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTestMem_Debug_x64.xml"
          type "${env:RUNNER_TEMP}/GTestMem_Debug_x64.xml"
      - name: Merge reports
        run: |
          npm install -g junit-report-merger
          jrm combined_Debug_x64.xml "${env:RUNNER_TEMP}/*_Debug_x64.xml"
          type combined_Debug_x64.xml
      - name: Public reports
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: combined_Debug_x64.xml
