name: Google Test
on: [workflow_dispatch]
jobs:
  google-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: 2.7
      - uses: actions/cache@v3
        with:
            path: ${{ env.pythonLocation }}
            key: ${{ env.pythonLocation }}-${{ hashFiles("setup.py") }}-${{ hashFiles("dev-requirements.txt") }}
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: pwsh
        run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}
      - name: Setup cache npm
        uses: actions/cache@v3
        id: npm-cache # use this to check for "cache-hit" ==> if: steps.npm-cache.outputs.cache-hit != "true"
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles("**/package-lock.json") }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build tests
        run: MSBuild qa/UnitTest/GTestMem -m -p:Configuration=Debug -p:Platform=x86
      - name: Run tests and collect reports
        run: ."${env:GITHUB_WORKSPACE}\qa\UnitTest\GTestMem\bin\Debug\GTestMem.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTestMem_Debug_x64.xml"
      - name: Merge reports
        run: |
          npm install -g junit-report-merger
          jrm combined_Debug_x64.xml "${env:RUNNER_TEMP}/*_Debug_x64.xml"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: combined_Debug_x64.xml
      # check python cache
      - name: Public reports
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: combined_Debug_x64.xml
