name: Google Test
on: [workflow_dispatch]
jobs:
  google-tests:
    runs-on: windows-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: read # for "actions/checkout@v3" when GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: artifact-all-tests-builded
          path: D:\a\turbo-octo-adventure\turbo-octo-adventure\qa\UnitTest\bin\Debug # build from *.sln
          search_artifacts: true
      - uses: actions/setup-python@v4
        id: cp310
        with:
          python-version: 3.10
#          cache: 'pip'
      - name: Setup cache python
        uses: actions/cache@v3
        with:
            path: ${{ env.pythonLocation }}
            key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
      - name: Check cache hit
        run: echo '${{ steps.cp310.outputs.cache-hit }}'

#      - name: Add MSBuild to PATH
#        uses: microsoft/setup-msbuild@v1.1
#      - name: Build tests
#        run: MSBuild qa/UnitTest -m -p:Configuration=Debug -p:Platform=x86
#      - uses: actions/upload-artifact@v3
#        with:
#          name: artifact-all-tests-builded
#          path: |
#            D:\a\turbo-octo-adventure\turbo-octo-adventure\qa\UnitTest\bin\Debug\StaticLibrary.lib
#            D:\a\turbo-octo-adventure\turbo-octo-adventure\qa\UnitTest\bin\Debug\GTest1.exe
#            D:\a\turbo-octo-adventure\turbo-octo-adventure\qa\UnitTest\bin\Debug\GTestDefWindowProc.exe
#            D:\a\turbo-octo-adventure\turbo-octo-adventure\qa\UnitTest\bin\Debug\GTestEmptyWorkingSet.exe
#            D:\a\turbo-octo-adventure\turbo-octo-adventure\qa\UnitTest\bin\Debug\GTestMem.exe

      - name: Run tests and collect reports
        # double run GTest1
        run: |
          ."${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\GTest1.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTest1_Debug_x86.xml"
          ."${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\GTest1.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTest1_Debug_x86.xml"
          ."${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\GTestDefWindowProc.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTestDefWindowProc_Debug_x86.xml"
          ."${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\GTestEmptyWorkingSet.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTestEmptyWorkingSet_Debug_x86.xml"
          ."${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\GTestMem.exe" --gtest_brief=1 --gtest_output="xml:${env:RUNNER_TEMP}/GTestMem_Debug_x86.xml"
      - name: Merge reports
        run: |
          pip install junitparser
          junitparser merge --suite-name AllTests --glob "${env:RUNNER_TEMP}\*_Debug_x86.xml" "combined_Debug_x86.xml"
          jrm "combined_Debug_x86.xml" $back_slashes_to_forward_slashes
      - name: Install converter to html and run convert
        run: |
          git clone https://github.com/burlachenkok/gtest_report
          # directory html_resources must be in current dir
          py --version
          py "gtest_report\scripts\genHtmlReportFromGtest.py" "out/gtest_report.html" "combined_Debug_x86.xml"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            combined_Debug_x86.xml
            out/
