name: Google Test
on: [workflow_dispatch]
jobs:
  google-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[16.11,16.12)'
      - name: Build test
        run: MSBuild qa\UnitTest -p:Configuration=Debug;Platform=x86
