name: Make test coverage from OpenCppCoverage (debug-x86)
on: [push,workflow_dispatch]
env: # build from *.sln, debug-x86
  dirTestsExe: '${{github.workspace}}\qa\UnitTest\bin\Debug\'
jobs:
  test-coverage:
    runs-on: windows-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: read # for "actions/checkout@v3" when GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: artifact-build-tests-debug-x86
          path: ${{github.workspace}}\qa\UnitTest\bin\Debug # build from *.sln
          search_artifacts: true

      - name: Download Open_Cpp_Coverage
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "OpenCppCoverage/OpenCppCoverage"
          latest: true
          fileName: "OpenCppCoverageSetup-x86*.exe"

      - name: Install Open Cpp Coverage
        shell: cmd
        run: |
          .\OpenCppCoverageSetup-x86-0.9.9.0.exe /VERYSILENT /DIR="Occ"
          dir ${{github.workspace}}\Occ
      - name: Run Open_Cpp_Coverage
        env:
            module0: GTest1.exe
        run: |
          cd src
          echo --modules ${env:module0} --excluded_sources "src\Main.h" --excluded_line_regex .*@NOCOVERAGE.* --export_type html:Coverage -- ${env:dirTestsExe}${env:module0}
          .${{github.workspace}}\Occ\OpenCppCoverage.exe --modules ${env:module0} --excluded_sources "src\Main.h" --excluded_line_regex .*@NOCOVERAGE.* --export_type html:Coverage -- ${env:dirTestsExe}${env:module0}

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-tests-coverage-open-cpp-coverage
          path: Coverage/
