name: Make test coverage from OpenCppCoverage (debug-x86)
on: [workflow_dispatch]
env: # build from *.sln, debug-x86
  dirTestsExe0: '${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\'
  dirTestsExe1: "${env:GITHUB_WORKSPACE}"
  dirTestsExe2: ${env:GITHUB_WORKSPACE}\qa\UnitTest\bin\Debug\
jobs:
  google-tests:
    runs-on: windows-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
    steps:
#      - uses: actions/checkout@v3 #?

#      - name: Download artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          github_token: ${{secrets.GITHUB_TOKEN}}
#          workflow: googletest.yml
#          name: artifact-build-tests-debug-x86
#          path: ${{github.workspace}}\qa\UnitTest\bin\Debug # build from *.sln
#          search_artifacts: true

      - name: Show env
        run: |
            echo 'dirTestsExe0 :'$dirTestsExe0
            echo 'dirTestsExe0 :'$dirTestsExe1
            echo 'dirTestsExe0 :'$dirTestsExe2

#      - name: Install OpenCppCoverage
#        - uses: robinraju/release-downloader@v1.8
#          with:
#            repository: "OpenCppCoverage/OpenCppCoverage"
#            latest: true

      - name: Install OpenCppCoverage
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: "OpenCppCoverage/OpenCppCoverage"
          cache: enable

      - name: Run OpenCppCoverage
        run: |
          # build from *.sln # double because windows system hooks from AppCompat conflicts with gmock-win32 hooks
          OpenCppCoverage.exe

#      - uses: actions/upload-artifact@v3
#        with:
#          name: artifact-tests-coverage-open-cpp-coverage
#          path: gtest_report/out/
