name: Run tests, then collect result and coverage
on: { push: { paths-ignore: README.md }, workflow_dispatch }
# Configuration
env:
  strPlatform: x86 # or x64
  strConfiguration: Debug # or Release
  strNameOccSetupFile: OpenCppCoverageSetup-x86-0.9.9.0.exe
  strGhTagOccSetupFile: release-0.9.9.0 # from https://github.com/OpenCppCoverage/OpenCppCoverage/tags
  strOccExecutable: OpenCppCoverage.exe
  relHtmlReport: HtmlReportOcc
  strCoberturaReport: CoberturaReportOcc.xml
  relGtestOutput: GtestOutput
  module0: GTest1.exe
  module1: GTestDefWindowProc.exe
  module2: GTestEmptyWorkingSet.exe
  module3: GTestMem.exe
jobs:
  collect-tests-code-coverage:
    runs-on: windows-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: read # for "actions/checkout@v3" when GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v3

      - name: Set values (windows-latest)
        run: | # build from *.sln, all tests
          echo "dirTestExecutables=${{github.workspace}}\qa\UnitTest\bin\${{env.strPlatform}}\${{env.strConfiguration}}" >> $env:GITHUB_ENV
          echo "dirSetupOcc=${env:Programfiles}\Occ" >> $env:GITHUB_ENV
          echo "strCfg=${{env.strPlatform}}-${{env.strConfiguration}}" >> $env:GITHUB_ENV

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-tests-gtest-debug-x86.yml
          name: artifact-build-tests-gtest-${{env.strCfg}}
          path: ${{env.dirTestExecutables}}
          search_artifacts: true

      - name: Cache tool
        uses: actions/cache@v3
        with:
          path: ${{env.dirSetupOcc}}
          key: cache-key-tool-occ-${{env.strNameOccSetupFile}}
        id: cache-tool-occ
      - name: Download tool
        if: steps.cache-tool-occ.outputs.cache-hit != 'true'
        uses: robinraju/release-downloader@v1.8
        with:
          repository: OpenCppCoverage/OpenCppCoverage
          fileName: ${{env.strNameOccSetupFile}}
          tag: ${{env.strGhTagOccSetupFile}}
      - name: Install tool
        if: steps.cache-tool-occ.outputs.cache-hit != 'true'
        run: |
          $arglist="/VERYSILENT /SUPPRESSMSGBOXES /DIR=""${{env.dirSetupOcc}}"" /LOG=""${{runner.temp}}\${{env.strNameOccSetupFile}}.log"""
          Start-Process "${{env.strNameOccSetupFile}}" -ArgumentList $arglist -Wait 
          #type "${{runner.temp}}\${{env.strNameOccSetupFile}}.log"

      - name: Run tool
        continue-on-error: true
        run: | # double launching because windows system hooks from AppCompat conflicts with gmock-win32 hooks
          @( 
              "${{env.module0}}"
            , "${{env.module1}}"
            , "${{env.module2}}"
            , "${{env.module3}}"
          ).ForEach{ Start-Process "${{env.dirTestExecutables}}\$_" -ArgumentList '--gtest_repeat=0' -NoNewWindow; } 
          
          $common_args='-q --working_dir "src"'
          $modules="--modules ${{env.dirTestExecutables}}"
          $sep = ' --excluded_sources '; $excluded_sources = $sep + ( '"{0}"' -f ( @( 
          'src\Main.h'
            , 'src\Legacy'
            , 'qa\UnitTest'
            , 'D:\a\_work'
            , 'C:\Program Files'
          ) -join '"'+$sep+'"') );
          $excluded_line_regex='--excluded_line_regex .*@NOCOVERAGE.*'
          Function runnerOcc_ ( $arg_program ) {
            $export_type="--export_type binary:${{runner.temp}}\${arg_program}.cov"
            $program_to_run="${{env.dirTestExecutables}}\$arg_program --gtest_brief=1 --gtest_output=xml:${{runner.temp}}\${{env.relGtestOutput}}\$arg_program.xml"
            Start-Process -Wait -NoNewWindow "${{env.dirSetupOcc}}\${{env.strOccExecutable}}" -ArgumentList "$common_args $modules $excluded_sources $excluded_line_regex $export_type -- $program_to_run"
          }          
          runnerOcc_ ${{env.module0}}
          runnerOcc_ ${{env.module1}}
          runnerOcc_ ${{env.module2}}
          runnerOcc_ ${{env.module3}}
          
          # Change html template
          $ffnOccTemplate="${{env.dirSetupOcc}}\Template\MainTemplate.html"
          (Get-Content $ffnOccTemplate).replace('{{TITLE}}', 'Merged from all tests') | Set-Content $ffnOccTemplate
          
          $export_type="--export_type html:${{runner.temp}}\${{env.relHtmlReport}} --export_type cobertura:${{runner.temp}}\${{env.strCoberturaReport}}"
          $sep = " --input_coverage ${{runner.temp}}\"; 
          $input_coverage = $sep + ( @(
              "${{env.module0}}.cov"
            , "${{env.module1}}.cov"
            , "${{env.module2}}.cov"
            , "${{env.module3}}.cov"
          ) -join $sep );
          Start-Process -Wait -NoNewWindow "${{env.dirSetupOcc}}\${{env.strOccExecutable}}" -ArgumentList "$input_coverage $export_type" 
          
          [xml]$oSystem_Xml_XmlDocument = Get-Content ${{runner.temp}}\${{env.strCoberturaReport}};
          $oSystem_Xml_XmlElement = $oSystem_Xml_XmlDocument.GetElementsByTagName( 'coverage' ).Item( 0 );
          $uLinesCovered = $oSystem_Xml_XmlElement.GetAttribute( 'lines-covered' );
          $uLinesValid = $oSystem_Xml_XmlElement.GetAttribute( 'lines-valid' );
          $dCoveredPercent = ( 100 * ( $uLinesCovered / $uLinesValid ) );
          $strCoveredPercent = [math]::Round( $dCoveredPercent, 2 );
          echo "strCoverageValue=$strCoveredPercent" >> $env:GITHUB_ENV

      - name: Generate *.svg file for badge if success
        if: ${{ success( ) }}
        uses: emibcn/badge-action@v2.0.2
        with:
          label: Tests coverage
          status: ${{env.strCoverageValue}}%
          color: ${{ false
            || env.strCoverageValue > 90 && 'green'
            || env.strCoverageValue > 80 && 'yellow,green'
            || env.strCoverageValue > 70 && 'yellow'
            || env.strCoverageValue > 60 && 'orange,yellow'
            || env.strCoverageValue > 50 && 'orange'
            || env.strCoverageValue > 40 && 'red,orange'
            || env.strCoverageValue > 30 && 'red,red,orange'
            || env.strCoverageValue > 20 && 'red,red,red,orange'
            || 'red' }}
          path: ${{runner.os}}-${{env.strCfg}}.svg
      # env-s not pass between steps when failure
      - name: Generate *.svg file for badge if failure
        if: ${{ failure( ) }}
        uses: emibcn/badge-action@v2.0.2
        with:
          label: Tests coverage
          status: failing
          color: red
          path: ${{runner.os}}-${{env.strCfg}}.svg

      - name: Put *.svg file to Gists for badge
        if: ${{ success( ) || failure( ) }} # yes, not 'always( )' because 'cancelled( )'
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.ACCESS_TO_GIST }}
          gist_id: 2af621bdd237231125e907ea81b1f8a8
          file_path: ${{runner.os}}-${{env.strCfg}}.svg

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - name: Install xml merger
        run: pip install junitparser
      - name: Merge xml reports
        run: junitparser merge --suite-name AllTests --glob "${{runner.temp}}\${{env.relGtestOutput}}\*.xml" "${{env.strCfg}}.xml"
      - name: Install gtest xml to html converter
        run: git clone https://github.com/Alexovsky5/gtest_report
      - name: Convert xml to html
        working-directory: ./gtest_report # directory html_resources must be in current dir
        run: |
          py scripts\genHtmlReportFromGtest.py "out\GoogleTestCombinedOutput.html" "..\${{env.strCfg}}.xml"
          mv -v "out" ${{runner.temp}}\GoogleTestCombinedOutput
          [xml]$oSystem_Xml_XmlDocument = Get-Content ..\${{env.strCfg}}.xml
          $oSystem_Xml_XmlElement = $oSystem_Xml_XmlDocument.GetElementsByTagName( 'testsuites' ).Item( 0 );
          $uTests = $oSystem_Xml_XmlElement.GetAttribute( 'tests' );
          echo "uTests=$uTests" >> $env:GITHUB_ENV

      - name: Generate *.svg file for badge2
        uses: emibcn/badge-action@v2.0.2
        with:
          label: GoogleTest
          status: ${{env.uTests}} testsuites
          path: GoogleTest-testsuites-${{runner.os}}-${{env.strCfg}}.svg
      - name: Put *.svg file to Gists for badge2
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.ACCESS_TO_GIST }}
          gist_id: 2af621bdd237231125e907ea81b1f8a8
          file_path: GoogleTest-testsuites-${{runner.os}}-${{env.strCfg}}.svg

      # - name: Install metrics code
        # run: pip install metrixpp
#-old
      - name: Install metrics code
        run: git clone https://github.com/metrixplusplus/metrixplusplus metrixplusplus
      - name: Run metrics code
        continue-on-error: true
        run: |
          py metrixplusplus\metrix++.py collect --std.code.lines.code --std.code.complexity.cyclomatic --db-file=${{runner.temp}}\metrixpp.db -- ${{github.workspace}}\src
          py metrixplusplus\metrix++.py view --db-file=${{runner.temp}}\metrixpp.db > ${{runner.temp}}\metrixpp_view.txt

      - name: Linter source code to job summary
        continue-on-error: true
        uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra-args: -std=c++14
          style: ''
          repo-root: src
          ignore: Legacy
          step-summary: true
          file-annotations: false
          files-changed-only: false

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-coverage-tests-OpenCppCoverage-${{env.strCfg}}
          path: |
            ${{runner.temp}}\${{env.relHtmlReport}}
            ${{runner.temp}}\GoogleTestCombinedOutput
            ${{runner.temp}}\metrixpp_view.txt
